export interface requsiciones {
    usuario:string;
    adaptable_a_cambios: number;
    asertividad: number;
    clasificacion_y_orden_logico: number;
    colaborador: number;
    compresion_verbal: number;
    concentracion: number;
    conocimientos_previos: string;
    creatividad: number;
    datos_puesto_id: number;
    dominio_publico: number;
    empatico: number;
    emprendedor: number;
    estado_civil: string;
    facilidad_de_palabra: number;
    fecha_solicitud: string;
    horario_dias_laborales: string;
    id: number;
    iniciativa: number;
    manejo_de_estres: number;
    manejo_de_personal: number;
    motivo_vacante: string;
    negociacion: number;
    nivel_estudios_minimo: string;
    no_vacante: number;
    nombre_solicitante: string;
    nombre_vacante: string;
    objetividad_en_manejo_informacion: number;
    orientado_a_resultados: number;
    poder_personal: number;
    presupuesto: number | null;
    publicacion_vacante: string;
    puesto_id: number;
    puesto_solicitante: string;
    rango_edad: string;
    region_solicitante: string;
    requerimientos_adicionales: string;
    requiere_dominio_idiomas: number;
    responsable: number;
    salario: string;
    seguimiento_de_instrucciones: number;
    sentido_de_pertenencia: number;
    sexo: string;
    tiempo_minimo_experiencia: string;
    toma_de_decisiones: number;
    trabajo_en_equipo: number;
  }
  